export const ADD_FRUIT = "ADD_FRUIT" ;
export const DELETE_FRUIT = "DELETE_FRUIT";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY"
export const DECREMENT_FRUIT = "DECREMENT_FRUIT"
export const CLEAR_FRUIT = "CLEAR_FRUIT"
export const UPDATE_QUANTITY = "UPDATE_QUANTITY"